# Site settings
name: Patrick Nugros
title: Patrick Nugros | Tenaga Kerja Digital
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://patricknugros.com/
baseurl: ''
email: mail@patricknugros.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:mail@patricknugros.com
  - title: twitter
    url: https://twitter.com/patricknugros
  - title: instagram
    url: https://instagram.com/patricknugros
  - title: github
    url: https://github.com/patricknugros

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
