# Site settings
name: Patrick Nugros
title: Patrick Nugros
description: Tenaga Kerja Digital
url: https://patricknugros.com
baseurl: ''
email: mail@patricknugros/com
cover: https://patricknugros.com/img/og.png
logo: https://patricknugros.com/img/emojis/technologist.png
resume: https://docs.google.com/document/d/1RkqY0OBOv-cb-8UdiZ7IleIa0-54sK5Iu0fcGb5FWYQ/edit?usp=sharing
social:
  - title: email
    url: mailto:mail@patricknugros.com
  - title: twitter
    url: https://twitter.com/patricknugros
  - title: instagram
    url: https://instagram.com/patricknugros
  - title: github
    url: https://github.com/patricknugros

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
