# Site settings
name: Putranto Adhi Nugroho
title: Putranto Adhi Nugroho
description: 
url: https://adhinugroho.com
baseurl: ''
email: putranto@adhinugroho.com
cover: https://adhinugroho.com/img/og.png
logo: https://adhinugroho.com/img/emojis/technologist.png
resume: https://docs.google.com/document/d/1RkqY0OBOv-cb-8UdiZ7IleIa0-54sK5Iu0fcGb5FWYQ/edit?usp=sharing
social:
  - title: email
    url: mailto:putranto@adhinugroho.com
  - title: twitter
    url: https://twitter.com/putrantoan
  - title: instagram
    url: https://instagram.com/putrantoan
  - title: github
    url: https://github.com/putrantoan
 - title: linkedin
    url: https://www.linkedin.com/in/putranto-adhi-nugroho-82589039/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

# Google Analytics
google_analytics: UA-158105216-1